name: rohan_suraksha_sathi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  connectivity_plus: ^6.1.1
  multi_select_flutter: ^4.0.0
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  signature: ^5.5.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  geocoding: ^3.0.0
  flutter_local_notifications: ^18.0.1
  restart_app: ^1.3.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/form.json
  #   - images/a_dot_ham.jpeg

flutter_native_splash:
  color: "#ffffff"  # Background color of the splash screen (use a hex color code or color name)
  image: assets/rohan_logo.png  # Path to the splash image file
  #fill: false Whether to stretch the image to fill the screen
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS
  android_gravity: center  # Aligns the image in the center of the screen
  ios_content_mode: scaleAspectFill  # Ensures the image scales proportionally on iOS

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
